// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wybory.Web.Dane;

#nullable disable

namespace Wybory.Web.Migrations
{
    [DbContext(typeof(BazaDanych))]
    [Migration("20260831070515_PoczatkowaBaza")]
    partial class PoczatkowaBaza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Wybory.Web.Dane.Glos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOddania")
                        .HasColumnType("TEXT");

                    b.Property<int>("KandydatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WyborcaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KandydatId");

                    b.HasIndex("WyborcaId")
                        .IsUnique();

                    b.ToTable("Glosy");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Kandydat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KomitetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumerNaLiscie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OkregId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WyborcaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KomitetId");

                    b.HasIndex("OkregId");

                    b.HasIndex("WyborcaId")
                        .IsUnique();

                    b.ToTable("Kandydaci");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Komitet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nazwa")
                        .IsUnique();

                    b.ToTable("Komitety");
                });

            modelBuilder.Entity("Wybory.Web.Dane.KomitetOkreg", b =>
                {
                    b.Property<int>("KomitetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OkregId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KomitetId", "OkregId");

                    b.HasIndex("OkregId");

                    b.ToTable("KomitetyOkregow");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Okreg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiczbaMandatow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Okregi");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Wyborca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BierneProwoWyborcze")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzynnePrawoWyborcze")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OkregId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OkregId");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("Wyborcy");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Glos", b =>
                {
                    b.HasOne("Wybory.Web.Dane.Kandydat", "Kandydat")
                        .WithMany("Glosy")
                        .HasForeignKey("KandydatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wybory.Web.Dane.Wyborca", "Wyborca")
                        .WithOne("Glos")
                        .HasForeignKey("Wybory.Web.Dane.Glos", "WyborcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kandydat");

                    b.Navigation("Wyborca");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Kandydat", b =>
                {
                    b.HasOne("Wybory.Web.Dane.Komitet", "Komitet")
                        .WithMany("Kandydaci")
                        .HasForeignKey("KomitetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wybory.Web.Dane.Okreg", "Okreg")
                        .WithMany("Kandydaci")
                        .HasForeignKey("OkregId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wybory.Web.Dane.Wyborca", "Wyborca")
                        .WithOne("Kandydatura")
                        .HasForeignKey("Wybory.Web.Dane.Kandydat", "WyborcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Komitet");

                    b.Navigation("Okreg");

                    b.Navigation("Wyborca");
                });

            modelBuilder.Entity("Wybory.Web.Dane.KomitetOkreg", b =>
                {
                    b.HasOne("Wybory.Web.Dane.Komitet", "Komitet")
                        .WithMany("Okregi")
                        .HasForeignKey("KomitetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wybory.Web.Dane.Okreg", "Okreg")
                        .WithMany("KomitetyOkregu")
                        .HasForeignKey("OkregId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Komitet");

                    b.Navigation("Okreg");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Wyborca", b =>
                {
                    b.HasOne("Wybory.Web.Dane.Okreg", "Okreg")
                        .WithMany("Wyborcy")
                        .HasForeignKey("OkregId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Okreg");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Kandydat", b =>
                {
                    b.Navigation("Glosy");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Komitet", b =>
                {
                    b.Navigation("Kandydaci");

                    b.Navigation("Okregi");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Okreg", b =>
                {
                    b.Navigation("Kandydaci");

                    b.Navigation("KomitetyOkregu");

                    b.Navigation("Wyborcy");
                });

            modelBuilder.Entity("Wybory.Web.Dane.Wyborca", b =>
                {
                    b.Navigation("Glos");

                    b.Navigation("Kandydatura");
                });
#pragma warning restore 612, 618
        }
    }
}
